# Generated by Django 4.0.3 on 2022-03-11 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree a')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis a jour a')),
                ('amount', models.IntegerField(verbose_name='montant')),
                ('payment_due_date', models.DateTimeField(verbose_name='date de paiement')),
                ('is_signed', models.BooleanField(default=False, verbose_name='est signe')),
                ('is_paid', models.BooleanField(default=False, verbose_name='est payé')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='client')),
                ('sales_contact', models.ForeignKey(error_messages={'limit_choices_to': 'This user is not part of the sales team.'}, limit_choices_to={'role': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sales contact')),
            ],
            options={
                'verbose_name': 'contrat',
                'verbose_name_plural': 'contrats',
            },
        ),
    ]
